### ISSUE TITLE
Unable to do simple GET request

### ISSUE THREAD

**Issue by tripodsan** [node-app/Nodelike#50]
Hi, I'm trying the do a simple http.get request:

```
var http = require('http');
http.get("http://www.google.com/index.html", function(res) {
         console.log("Got response: " + res.statusCode);
}).on('error', function(e) {
         console.log("Got error: " + e.message);
});
```

but the execution just stalls. I see on my own server that the socket is established, but no data is sent.
this is the objc code I use to execute the script:

```
    JSVirtualMachine* vm = [[JSVirtualMachine alloc]init];
    JSContext *context = [[JSContext alloc] initWithVirtualMachine:vm];
    [NLContext attachToContext:context];
    NSString *initjs = [NSString stringWithContentsOfFile:[[NSBundle mainBundle] pathForResource:@"init" ofType:@"js"] encoding:(NSUTF8StringEncoding) error:NULL];
    [context evaluateScript:initjs];
    [NLContext runEventLoopAsyncInContext:context];
```

I can only assume that some events are not processed.
thanks.

**Comment by BlackWolf** [comment]
I can't test your code right now but just from looking at my own code I think there might be two issues here:

1) You are initializing a `JSContext`, try initializing a `NLContext` instead
2) Try saving your context into an instance property with attribute `retain` - it might be that the garbage collector collects your context after your method finished and therefore stops execution (I had a similar issue using `CBPeripheralManager`)

**Comment by tripodsan** [comment]
thanks @BlackWolf. I did some changes but the request is still stuck. https://gist.github.com/tripodsan/8ea074710e6ab40ecab1

**Comment by zetachang** [comment]
Same here :cry:
