### ISSUE TITLE
Is possible create native addon inside context with Swift?

### ISSUE THREAD

**Issue by gabrielbiga** [node-app/Nodelike#52]
I'm trying create a new addon inside my NLContext with Swift.

In documentation:
```
context[@"myAwesomeFunction"] = ^{
  [MyAwesomeAddon doAThing]; 
  return @"Hello World";
};
```

I'm trying with this code bellow:
```
context["cool"] = {
    ()  in
    println( "Hello" )
}
```
And i getting the error:  'NLContext' does not have a member named 'subscript'

Is possible do that in Swift?

**Comment by srijs** [comment]
Hi there. This project is basically unmaintained right now, so I'm unable to help you in depth. It looks like Swifts subscripting is not 100% compatible with Objective C in this case. Maybe try invoking `context setObject:... forKeyedSubscript:"cool"` manually?

**Comment by gabrielbiga** [comment]
I got this:

```
var coolMethod : @objc_block ( JSValue! ) -> Void = {
    ( message: JSValue! ) -> Void in

     println( "Cool func! " + message )
}

_context.setObject( unsafeBitCast( coolMethod, AnyObject.self ), forKeyedSubscript: "cool" )
```

It works.
Thanks @srijs!
